### ISSUE TITLE
fluidity: symbol lookup error: /usr/lib64/openmpi/lib/libptscotch.so.0: undefined symbol: _SCOTCHorderSaveTree

### ISSUE THREAD

**Issue by conquer001** [FluidityProject/fluidity#67] opened 2015-09-04 09:14 UTC
My OS is Centos6.7 64bit
 I have installed fluidity in my computer with "yum install fuidity"   , it told me flnished 
but when I run fluidity with ,there is an error ,it seems like  there is something wrong with openmpi

fluidity: symbol lookup error: /usr/lib64/openmpi/lib/libptscotch.so.0: undefined symbol: _SCOTCHorderSaveTree

**Comment by tmbgreaves** [comment] 2015-09-05 09:45
Confirmed this end CentOS 6 is picking up a different version of scotch by default rather than ours. The packages you need for Fluidity should be able to be installed with:

yum install https://github.com/FluidityProject/yum-rhel6/raw/master/x86_64/scotch-6.0.0-2.el6.x86_64.rpm https://github.com/FluidityProject/yum-rhel6/raw/master/x86_64/scotch-devel-6.0.0-2.el6.x86_64.rpm

It looks like EPEL has moved to 6.0.4 which 'upgrades' from our 6.0.0 package. I think the fix for this is going to be for me to rebuild the scotch package with a different name (probably as per OpenFOAM, and call it fluidity-scotch) but in the interim if you can force install of the above packages I think it will resolve the problem.

Unfortunately I am about to be on leave for three weeks and will probably not get a chance to sort this out until first week of October, but I'll assign this to me to fix when I return.

**Comment by tmbgreaves** [comment] 2016-02-16 15:41
This should now be resolved with a complete overhaul of the PETSc packaging for CentOS, which wraps the scotch build into the PETSc package rather than using a separate package, avoiding the problem of our version being older than the system version.

**Closed by tmbgreaves** 2016-02-16 15:41 UTC
