### ISSUE TITLE
master does not build anymore

### ISSUE THREAD

**Issue by Patol75** [FluidityProject/fluidity#204] opened 2018-06-11 06:49 UTC
Dear all,

Following a ```git pull``` today, the master branch of Fluidity failed to build on my system. Investigating the few recent commits, it appears that 111f2ec from @jrper is the first one on which the error shows up.
My system setup is the same as what is described in #192 and the error shows up both on Ubuntu 16.04 and 18.04 (for 18.04, I switch to the https://github.com/FluidityProject/fluidity/tree/FixTests branch for example and then do a ```git merge master```, which results in the same failure; note however that only switching to the https://github.com/FluidityProject/fluidity/tree/bionic_workaround branch for example gives a successful build). Please see below for the error.

Thomas
```
./src/ErrorMeasure.cpp: In member function ‘void ErrorMeasure::apply_gradation(double)’:
./src/ErrorMeasure.cpp:152:21: error: invalid use of incomplete type ‘class vtkTriangle’
           NNList[tri->GetPointId(i)].insert(tri->GetPointId(j));
                     ^
In file included from /usr/include/vtk-6.2/vtkPolyDataAlgorithm.h:33:0,
                 from /usr/include/vtk-6.2/vtkContourGrid.h:50,
                 from /home/thomas/Softwares/fluidity/include/vtk.h:12,
                 from ./include/ErrorMeasure.h:42,
                 from ./src/ErrorMeasure.cpp:29:
/usr/include/vtk-6.2/vtkPolyData.h:67:7: note: forward declaration of ‘class vtkTriangle’
 class vtkTriangle;
       ^
./src/ErrorMeasure.cpp:152:48: error: invalid use of incomplete type ‘class vtkTriangle’
           NNList[tri->GetPointId(i)].insert(tri->GetPointId(j));
                                                ^
In file included from /usr/include/vtk-6.2/vtkPolyDataAlgorithm.h:33:0,
                 from /usr/include/vtk-6.2/vtkContourGrid.h:50,
                 from /home/thomas/Softwares/fluidity/include/vtk.h:12,
                 from ./include/ErrorMeasure.h:42,
                 from ./src/ErrorMeasure.cpp:29:
/usr/include/vtk-6.2/vtkPolyData.h:67:7: note: forward declaration of ‘class vtkTriangle’
 class vtkTriangle;
       ^
./src/ErrorMeasure.cpp:153:21: error: invalid use of incomplete type ‘class vtkTriangle’
           NNList[tri->GetPointId(j)].insert(tri->GetPointId(i));
                     ^
In file included from /usr/include/vtk-6.2/vtkPolyDataAlgorithm.h:33:0,
                 from /usr/include/vtk-6.2/vtkContourGrid.h:50,
                 from /home/thomas/Softwares/fluidity/include/vtk.h:12,
                 from ./include/ErrorMeasure.h:42,
                 from ./src/ErrorMeasure.cpp:29:
/usr/include/vtk-6.2/vtkPolyData.h:67:7: note: forward declaration of ‘class vtkTriangle’
 class vtkTriangle;
       ^
./src/ErrorMeasure.cpp:153:48: error: invalid use of incomplete type ‘class vtkTriangle’
           NNList[tri->GetPointId(j)].insert(tri->GetPointId(i));
                                                ^
In file included from /usr/include/vtk-6.2/vtkPolyDataAlgorithm.h:33:0,
                 from /usr/include/vtk-6.2/vtkContourGrid.h:50,
                 from /home/thomas/Softwares/fluidity/include/vtk.h:12,
                 from ./include/ErrorMeasure.h:42,
                 from ./src/ErrorMeasure.cpp:29:
/usr/include/vtk-6.2/vtkPolyData.h:67:7: note: forward declaration of ‘class vtkTriangle’
 class vtkTriangle;
       ^
./src/ErrorMeasure.cpp: In member function ‘int ErrorMeasure::grad(std::__cxx11::string)’:
./src/ErrorMeasure.cpp:486:3: error: ‘vtkExtractVectorComponents’ was not declared in this scope
   vtkExtractVectorComponents *components = vtkExtractVectorComponents::New();
   ^
./src/ErrorMeasure.cpp:486:31: error: ‘components’ was not declared in this scope
   vtkExtractVectorComponents *components = vtkExtractVectorComponents::New();
                               ^
./src/ErrorMeasure.cpp:486:44: error: ‘vtkExtractVectorComponents’ is not a class or namespace
   vtkExtractVectorComponents *components = vtkExtractVectorComponents::New();
                                            ^
<builtin>: recipe for target 'ErrorMeasure.o' failed
make[2]: *** [ErrorMeasure.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

**Comment by jrper** [comment] 2018-06-11 07:00
Hi @Patol75, just to confirm, are you performing a run of `./configure; make clean;` before you attempt to build master? That changeset doesn't directly modify the file which is throwing the error, but might easily cause issues if you're reconfiguring without building from scratch.

**Comment by Patol75** [comment] 2018-06-11 07:07
This is the command I use for building:
```
./configure --enable-2d-adaptivity --enable-debugging LDFLAGS="-L/usr/local/lib" FCFLAGS="-I/usr/local/include" CPPFLAGS="-I/usr/local/include" && sudo make clean && make -j && make -j fltools && sudo make -j install
```

**Comment by jrper** [comment] 2018-06-11 07:40
That ought to force a fresh build indeed. Looking deeper, the proximate cause of the issue is that the build within the `libadaptivity/` directory is picking up the `vtk.h` header file from the main fluidity build at `/home/thomas/Softwares/fluidity/include/vtk.h`, rather than its own one at `libadaptivity/include/vtk.h`. What I'm less sure about is why (or at least why we weren't seeing that on our systems, including the Jenkins CI build).

**Comment by Patol75** [comment] 2018-06-11 07:51
Thank you for spotting that James. Is there any chance that it could be triggered by this change:
https://github.com/FluidityProject/fluidity/commit/111f2ec5675f6643b4033b31b060c238f5bc8047#diff-e2d5a00791bce9a01f99bc6fd613a39d ?

**Comment by jrper** [comment] 2018-06-11 07:57
Yes, but possibly only in the sense of two wrongs having previously caused a right. One of the modifications to the main fluidity configure script there stopped it from spuriously including nonexistent `include` directories all over the place, which generated an amazing number of meaningly warnings at compile time, but it's possible that for you, that's happening to force the compiler to find the correct version of that specific header file, at the time you needed it.

**Comment by stephankramer** [comment] 2018-06-11 09:36
Looking at the diff between include/vtk.h and libadaptivity/include/vtk.h, we should probaly just
add:

#include <vtkExtractVectorComponents.h>
#include <vtkTriangle.h>

to include/vtk.h ?

**Comment by jrper** [comment] 2018-06-11 09:40
That would certainly clear the build error. It would be kind of nice to understand what's going wrong though.

**Comment by stephankramer** [comment] 2018-06-11 10:57
Well the failing compilation happens from libadaptivity/ So I presume prior to your commit it was finding $srcdir/libadaptivity/include/vtk.h via the -Iinclude/ added in by fluidity's main configure, but afterwards that changed to -I$srcdir/include/

**Comment by jrper** [comment] 2018-06-11 12:34
I think we understand this a little bit better now. It looks like if `CPPFLAGS` is set at configure time, then the libadaptivity `configure` script inherits the entire content of that variable, which (post that commit) tells it to find that header in the wrong place. Meanwhile, if the variable isn't set (as in the Jenkins build, and most of the builds we run here) then nothing is passed on, and everything just works. Evidently, this has been a problem with fortran flags at some point, since there's something of a hack to prevent just this kind of behaviour. I'm attempting to port it over to the C/C++ side of things now.

**Comment by jrper** [comment] 2018-06-11 13:08
@Patol75 I've pushed the change to 7b6f6c6d12878079d071413499067d133375a505, is there any chance you can confirm whether it works for you? If so, we'll get this in as a bug fix ASAP.

**Comment by Patol75** [comment] 2018-06-12 02:53
Thank you for addressing the issue. The build passes on the libadaptivity_configure_fix branch. As a side comment, I notice a lot of ```Warning: Procedure ‘xyz’ called with an implicit interface at (1) [-Wimplicit-interface]``` during the make procedure, and I am not quite sure if those were present or not before.

**Comment by jrper** [comment] 2018-06-12 22:08
The change is in master, so I'm closing this now.

**Closed by jrper** 2018-06-12 22:08 UTC
