### ISSUE TITLE
Zoltan issues with empty partitions introduced between a2ecea and c6c446

### ISSUE THREAD

**Issue by tmbgreaves** [FluidityProject/fluidity#60] opened 2015-06-05 10:36 UTC
I'm seeing a bug in a number of our parallel short tests when run on CX1 with Intel and PETSc 3.5.2 (but not when run on workstations with GCC and Petsc 3.4.2), giving (in the example of 5material-droplet-parallel):
```
*** FLUIDITY ERROR ***
Source location: (Zoltan_integration.F90,  847)
Error message: After load balancing process would have an empty partition.
Backtrace will follow if it is available:
../../bin/flredecomp(fprint_backtrace_+0x2a) [0x88676a]
../../bin/flredecomp(fldebug_mp_flabort_pinpoint_+0x210) [0x4bfd00]
../../bin/flredecomp(zoltan_integration_mp_zoltan_drive_+0x2334) [0x8752a4]
../../bin/flredecomp(flredecomp+0x985) [0x4bc3f5]
../../bin/flredecomp(main+0xedb) [0x4bd4fb]
/lib64/libc.so.6(__libc_start_main+0xfd) [0x2ae0e42e4d5d]
../../bin/flredecomp() [0x4bb969]
Use addr2line -e <binary> <address> to decipher.
Error is terminal.
```
Full logs available at:

http://buildbot.ese.ic.ac.uk:8080/builders/5material-droplet-parallel/builds/299/steps/shell_5/logs/stdio

This appears to be a recent bug appearing with c6c446. a2ecea worked fine, c6c446 fails.

**Comment by stephankramer** [comment] 2015-06-05 12:21
Hm, I'm afraid that doesn't make any sense to me at all . That commit doesn't change anything to do with zoltan and or parmetis - and certainly the flredecomp never goes anywhere the 2 code lines that changed in that commit. So I'm a little stumped but I'll try to dig a little deeper.

**Comment by stephankramer** [comment] 2015-06-05 12:30
Hm, I'm afraid that doesn't make any sense to me at all . That commit doesn't change anything to do with zoltan and or parmetis - and certainly the flredecomp never goes anywhere the 2 code lines that changed in that commit. So I'm a little stumped but I'll try to dig a little deeper.

**Comment by stephankramer** [comment] 2015-06-05 12:35
Hi Tim (@tmbgreaves). Just had a chat with @jrper: our current most likely explanation is a change in environment that happened to coincide with that commit. If it's not to much work, would it be possible to rerun that test with a a2ecea to confirm that theory? If it's not something you could easily get done in a few minutes now - we'll have a look ourselves next week.

**Comment by jrper** [comment] 2015-06-05 14:24
I'm not sure whether it's relevant or not but it appears that the current fluidity build script uses 
module load parmetis
which pulls in the default version (3.1), whereas the zoltan library we're using is apparently built against parmetis 4.0.3.

**Comment by tmbgreaves** [comment] 2015-06-05 22:53
I'm afraid it's more than a few minutes - buildbot cleans up anything that hasn't been used in 72h - sorry.

**Comment by drhodrid** [comment] 2015-06-06 05:34
Hi all,

As I’ve been playing a bit with zoltan, parmetis and scotch recently, I’ve seen this error quite a few times. From my experience, it has (almost) always arisen due to a library issue (wrong parmetis version, linking two versions of parmetis etc…). What I’ve done in the past to quickly verify this is to change the flredecomp partitioner from parmetis (the default) to zoltan/hypergraph at the base of the .flml. After this change, the cases often worked.

R

---------------------------------------------------------------------------------------------------
ARC Future Fellow
Research School of Earth Sciences
The Australian National University
Canberra, ACT, 0200, Australia

T: +61 (0)2 6125 3643
E: rhodri.davies@anu.edu.au<mailto:rhodri.davies@anu.edu.au>
W: http://rses.anu.edu.au/people/dr-rhodri-davies
---------------------------------------------------------------------------------------------------

On 6 Jun 2015, at 08:53, Tim Greaves <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm afraid it's more than a few minutes - buildbot cleans up anything that hasn't been used in 72h - sorry.

**Comment by jrper** [comment] 2015-06-08 13:48
To update everyone, we believe that the issues on CX1 are the result of the inconsistency in parmetis versions between fluidity and zoltan caused by module files above, and similar issues for another developer on a different HPC cluster have been traced to a very similar problem, where the PETSc directory included a version of parmetis different from that used in the Zoltan build. If this does prove to fix the problem we'll try and ensure the CX1 documentation is updated appropriately. 

Outstanding points include:
1) does the same issue occur on CX2?
2) can the configure script be hardened to ensure that the version of parmetis fluidity is linked to, any version that petsc is linked to, and the version used to build zoltan are all identical?

**Comment by jrper** [comment] 2015-06-08 19:00
Thanks to @stephankramer's sharp eyes and access to the buildbot account, we now realise that the CX1 problem wasn't directly linked to parmetis after all, and was probably precipitated by a typo in a local build script. We hope this is fixed and if buildbot turns green over the next couple of days, we can close this issue. As a fringe benefit we are now testing with parmetis 4.0.3 on CX1.

**Closed** 2015-11-24 10:58 UTC
